# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "boa-home-task-TB"
client_id = "63ea075b807d6246854d17f581f784b1"
application_url = "https://tunnel-receiver-promising-manor.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers"

[auth]
redirect_urls = [
  "https://tunnel-receiver-promising-manor.trycloudflare.com/auth/callback",
  "https://tunnel-receiver-promising-manor.trycloudflare.com/auth/shopify/callback",
  "https://tunnel-receiver-promising-manor.trycloudflare.com/api/auth/callback",
  "https://tunnel-receiver-promising-manor.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "home-assignment-27.myshopify.com"
